// <auto-generated />
using System;
using ApiProyecto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiGenericaCsharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420155246_V12")]
    partial class V12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiProyecto.Models.Caracterizacion.AreaAplicacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("id");

                    b.ToTable("area_aplicacion");
                });

            modelBuilder.Entity("ApiProyecto.Models.Caracterizacion.AreaConocimiento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("area")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("disciplina")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("gran_area")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("id");

                    b.ToTable("area_conocimiento");
                });

            modelBuilder.Entity("ApiProyecto.Models.Caracterizacion.ObjetivoDesarrolloSostenible", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("id");

                    b.ToTable("objetivos_desarrollo_sostenible");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.AaRc", b =>
                {
                    b.Property<int>("actv_academicas_idcurso")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("registro_calificado_codigo")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("componente")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("semestre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("actv_academicas_idcurso", "registro_calificado_codigo");

                    b.ToTable("aa_rc");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Acreditacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("codigo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_ini")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hora_accion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("programa")
                        .HasColumnType("integer");

                    b.Property<string>("resolucion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo_situacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo_titulacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("acreditacion");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.ActvAcademica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("area_formacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("dinero")
                        .HasColumnType("integer");

                    b.Property<string>("diploma")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("entidad_Espejo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("h_acomp")
                        .HasColumnType("integer");

                    b.Property<int?>("h_indep")
                        .HasColumnType("integer");

                    b.Property<string>("idioma")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("num_creditos")
                        .HasColumnType("integer");

                    b.Property<string>("pais_apoyo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("actv_academica");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Aliado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("apellidos")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ciudad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("contacto")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("correo")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("empresa")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("id");

                    b.ToTable("aliado");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Alianza", b =>
                {
                    b.Property<int>("aliado")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("departamento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int?>("docente")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("aliado", "departamento");

                    b.ToTable("alianza");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.AnPrograma", b =>
                {
                    b.Property<int>("aspecto_normativo")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("programa")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("aspecto_normativo", "programa");

                    b.ToTable("an_programa");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.AspectoNormativo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("aspecto_norm_ac")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("id");

                    b.ToTable("aspecto_normativo");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.CarInnovacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("longtext")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("car_innovacion");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.DocenteDepartamento", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("departamento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("dedicacion")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("fecha_ingreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_salida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("modalidad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("docente", "departamento");

                    b.ToTable("docente_departamento");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Enfoque", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("enfoque");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.EnfoqueRc", b =>
                {
                    b.Property<int>("enfoque")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("registro_calificado")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("enfoque", "registro_calificado");

                    b.ToTable("enfoque_rc");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Facultad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("universidad")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("facultad");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Pasantia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("empresa")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("pais")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("programa")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("pasantia");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.PracticaEstrategia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("practica_estrategia");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Premio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("entidad_otorgante")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("pais")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("programa")
                        .HasColumnType("integer");

                    b.Property<double?>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("premio");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Programa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("cant_semestres")
                        .HasColumnType("integer");

                    b.Property<string>("ciudad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("facultad")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("num_creditos")
                        .HasColumnType("integer");

                    b.Property<string>("pais")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("programa");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.ProgramaAc", b =>
                {
                    b.Property<int>("programa")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_conocimiento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("programa", "area_conocimiento");

                    b.ToTable("programa_ac");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.ProgramaCi", b =>
                {
                    b.Property<int>("programa")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("car_innovacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("programa", "car_innovacion");

                    b.ToTable("programa_ci");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.ProgramaPe", b =>
                {
                    b.Property<int>("programa")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("practica_estrategia")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("programa", "practica_estrategia");

                    b.ToTable("programa_pe");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.RegistroCalificado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("calif_preg")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("cant_preg")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("docente_semestres")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("duracion_anios")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_ini")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("h_actv_academica")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("metodologia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("programa")
                        .HasColumnType("integer");

                    b.Property<string>("tipo_titulacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("registro_calificado");
                });

            modelBuilder.Entity("ApiProyecto.Models.Curricular.Universidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ciudad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("universidad");
                });

            modelBuilder.Entity("ApiProyecto.Models.Investigacion.OdsLinea", b =>
                {
                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("ods")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("linea_investigacion", "ods");

                    b.ToTable("ods_linea");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.ApoyoProfesoral", b =>
                {
                    b.Property<int>("estudios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("estudios"));

                    b.Property<bool?>("con_apoyo")
                        .HasColumnType("boolean");

                    b.Property<string>("institucion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("estudios");

                    b.ToTable("apoyo_profesoral");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.Beca", b =>
                {
                    b.Property<int>("estudios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("estudios"));

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institucion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("pais")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("estudios");

                    b.ToTable("beca");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.Docente", b =>
                {
                    b.Property<int>("cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cedula"));

                    b.Property<string>("apellidos")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("cargo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("cat_minciencia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("conv_minciencia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("correo")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("escalafon")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("genero")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int?>("linea_investigacion_principal")
                        .HasColumnType("integer");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombres")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("perfil")
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("url_cvlac")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("cedula");

                    b.ToTable("docente");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.EstudioAc", b =>
                {
                    b.Property<int>("estudio")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_conocimiento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("estudio", "area_conocimiento");

                    b.ToTable("estudio_ac");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.EstudiosRealizados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ciudad")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("docente")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("ins_acreditada")
                        .HasColumnType("boolean");

                    b.Property<string>("metodologia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("pais")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("perfil_egresado")
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("titulo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("universidad")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("estudios_realizados");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.EvaluacionDocente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float?>("calificacion")
                        .HasColumnType("real");

                    b.Property<int?>("docente")
                        .HasColumnType("integer");

                    b.Property<string>("semestre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("evaluacion_docente");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.Experiecia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("docente")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institucion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombre_cargo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("experiecia");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.InteresesFuturos", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<string>("termino_clave")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnOrder(1);

                    b.HasKey("docente", "termino_clave");

                    b.ToTable("intereses_futuros");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.Reconocimiento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ambito")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("docente")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("institucion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("reconocimiento");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.Red", b =>
                {
                    b.Property<int>("idr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idr"));

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("pas")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("uri")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("idr");

                    b.ToTable("red");
                });

            modelBuilder.Entity("ApiProyecto.Models.Profesional.RedDocente", b =>
                {
                    b.Property<int>("red")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("act_destacadas")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("red", "docente");

                    b.ToTable("red_docente");
                });

            modelBuilder.Entity("ApiProyecto.Models.Proyecto.OdsProyecto", b =>
                {
                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("ods")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("proyecto", "ods");

                    b.ToTable("ods_proyecto");
                });

            modelBuilder.Entity("ApiProyecto.Models.Proyecto.PalabrasClave", b =>
                {
                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<string>("termino_clave")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnOrder(1);

                    b.HasKey("proyecto", "termino_clave");

                    b.ToTable("palabras_clave");
                });

            modelBuilder.Entity("ApiProyecto.Models.Proyecto.ProyectoLinea", b =>
                {
                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("proyecto", "linea_investigacion");

                    b.ToTable("proyecto_linea");
                });

            modelBuilder.Entity("ApiProyecto.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.AaProyecto", b =>
                {
                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_aplicacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("proyecto", "area_aplicacion");

                    b.ToTable("aa_proyecto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.AcProyecto", b =>
                {
                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_conocimiento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("proyecto", "area_conocimiento");

                    b.ToTable("ac_proyecto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.AliadoProyecto", b =>
                {
                    b.Property<int>("aliado")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("aliado", "proyecto");

                    b.ToTable("aliado_proyecto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.Desarrolla", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("proyecto")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("rol")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("docente", "proyecto");

                    b.ToTable("desarrolla");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.DocenteProducto", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer");

                    b.Property<int>("producto")
                        .HasColumnType("integer");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.HasKey("docente", "producto");

                    b.ToTable("docente_producto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("proyecto")
                        .HasColumnType("integer");

                    b.Property<int?>("tipo_producto")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.Proyecto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("id");

                    b.ToTable("proyecto");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.TerminoClave", b =>
                {
                    b.Property<string>("termino")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnOrder(0);

                    b.Property<string>("termino_ingles")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("termino");

                    b.ToTable("termino_clave");
                });

            modelBuilder.Entity("ApiProyecto.Models.conocimiento.TipoProducto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("categoria")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("clase")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("nombre")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("tipologia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("tipo_producto");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.AcLinea", b =>
                {
                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_conocimiento")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("linea_investigacion", "area_conocimiento");

                    b.ToTable("ac_linea");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.AsLinea", b =>
                {
                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("area_aplicacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("linea_investigacion", "area_aplicacion");

                    b.ToTable("as_linea");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.GrupoInvestigacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ambito")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("categoria")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("convocatoria")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("fecha_fundacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("interno")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("universidad")
                        .HasColumnType("integer");

                    b.Property<string>("url_grupLAC")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("id");

                    b.ToTable("grupo_investigacion");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.GrupoLinea", b =>
                {
                    b.Property<int>("grupo_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("grupo_investigacion", "linea_investigacion");

                    b.ToTable("grupo_linea");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.LineaInvestigacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("id");

                    b.ToTable("linea_investigacion");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.ParticipaGrupo", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("grupo_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<string>("categoria")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("convocatoria")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_ini")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("docente", "grupo_investigacion");

                    b.ToTable("participa_grupo");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.ParticipaSemillero", b =>
                {
                    b.Property<int>("docente")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("semillero")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("fecha_ini")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("rol")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.HasKey("docente", "semillero");

                    b.ToTable("participa_semillero");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.Semillero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("fecha_fundacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("universidad")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("semillero");
                });

            modelBuilder.Entity("ApiProyecto.Models.investigacion.SemilleroLinea", b =>
                {
                    b.Property<int>("semillero")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("linea_investigacion")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("semillero", "linea_investigacion");

                    b.ToTable("semillero_linea");
                });
#pragma warning restore 612, 618
        }
    }
}
